// Ranges and display info for every tunable "game feel" number shown in the mobile
// tuning panel. Labels live in i18n under `tuning.<path>`. Values are stored in SI
// units (m, s, rad); `scale` converts to the displayed unit (e.g. rad → °).

export interface TuningParamMeta {
  /** "section.key" inside TUNING. */
  path: string;
  /** Range and step in DISPLAY units. */
  min: number;
  max: number;
  step: number;
  /** Display unit (not translated: SI symbols). */
  unit: string;
  /** stored × scale = displayed. Default 1. */
  scale?: number;
  /** i18n key of the label when shared between sections (default `tuning.<path>`). */
  labelKey?: string;
  /** Shown as a Sí/No switch (stored as 0 / 1). */
  toggle?: boolean;
}

export interface TuningSectionMeta {
  id: 'game' | 'skating' | 'cut' | 'dribble' | 'pass' | 'shot' | 'shotError' | 'volley' | 'receive' | 'wall' | 'assist' | 'passArrow' | 'mates' | 'ball' | 'input' | 'buttons' | 'camera' | 'cameraTv' | 'cameraClose' | 'cameraTactical';
  params: TuningParamMeta[];
}

const DEG = 180 / Math.PI;

/** Same parameters (and shared labels `tuning.cam.<key>`) for every camera preset. */
function cameraPresetParams(section: string): TuningParamMeta[] {
  const p = (key: string, min: number, max: number, step: number, unit: string, scale?: number): TuningParamMeta => ({
    path: `${section}.${key}`,
    min,
    max,
    step,
    unit,
    labelKey: `tuning.cam.${key}`,
    ...(scale === undefined ? {} : { scale }),
  });
  return [
    p('fov', 20, 80, 1, '°', DEG),
    p('height', 2, 35, 0.5, 'm'),
    p('distance', 3, 35, 0.5, 'm'),
    p('ballWeight', 0, 1, 0.05, ''),
    p('lookaheadTime', 0, 1, 0.05, 's'),
    p('smoothTime', 0.05, 1.5, 0.05, 's'),
    p('depthFollow', 0, 1, 0.05, ''),
    p('trackFactor', 0, 1, 0.02, ''),
    p('lookAcrossFactor', 0, 1, 0.05, ''),
    p('fovSpeedGain', 0, 15, 0.5, '°', DEG),
    p('fovSpeedRef', 3, 15, 0.5, 'm/s'),
    p('ballScale', 0.5, 3, 0.05, '×'),
  ];
}

/** Sections and parameters in the order shown (most impactful first). `sim` is not tunable. */
export const TUNING_SECTIONS: TuningSectionMeta[] = [
  {
    id: 'game',
    params: [{ path: 'game.speed', min: 80, max: 140, step: 5, unit: '%', scale: 100 }],
  },
  {
    id: 'skating',
    params: [
      { path: 'skating.maxSpeed', min: 4, max: 12, step: 0.1, unit: 'm/s' },
      { path: 'skating.sprintSpeed', min: 5, max: 14, step: 0.1, unit: 'm/s' },
      { path: 'skating.accel', min: 3, max: 25, step: 0.5, unit: 'm/s²' },
      { path: 'skating.accelCapFactor', min: 1.01, max: 1.3, step: 0.01, unit: '×' },
      { path: 'skating.maxTurnRate', min: 90, max: 900, step: 10, unit: '°/s', scale: DEG },
      { path: 'skating.turnRadiusBase', min: 0, max: 2, step: 0.05, unit: 'm' },
      { path: 'skating.turnRadiusPerSpeed2', min: 0, max: 0.2, step: 0.005, unit: 'm·s²/m²' },
      { path: 'skating.turnSpeedLoss', min: 0, max: 1.5, step: 0.05, unit: '/rad' },
      { path: 'skating.sprintBoostAccel', min: 0, max: 30, step: 0.5, unit: 'm/s²' },
      { path: 'skating.sprintBoostTime', min: 0, max: 0.6, step: 0.01, unit: 's' },
      { path: 'skating.sprintBoostOvershoot', min: 0, max: 2, step: 0.1, unit: 'm/s' },
      { path: 'skating.sprintBoostCooldown', min: 0, max: 3, step: 0.1, unit: 's' },
      { path: 'skating.skidTime', min: 0.2, max: 1.2, step: 0.02, unit: 's' },
      { path: 'skating.skidSlide', min: 0.4, max: 3, step: 0.05, unit: '' },
      { path: 'skating.skidBodyTurn', min: 0, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'skating.skidMinSpeed', min: 1, max: 15, step: 0.5, unit: 'm/s' },
      { path: 'skating.skidReleaseStick', min: 0.1, max: 1, step: 0.05, unit: '' },
      { path: 'skating.skidReleaseWindow', min: 0.03, max: 0.4, step: 0.01, unit: 's' },
      { path: 'skating.brakeAngle', min: 90, max: 180, step: 1, unit: '°', scale: DEG },
      { path: 'skating.glideDecel', min: 0, max: 3, step: 0.05, unit: 'm/s²' },
      { path: 'skating.glideDrag', min: 0, max: 1, step: 0.01, unit: '/s' },
      { path: 'skating.overspeedDecel', min: 0.5, max: 10, step: 0.1, unit: 'm/s²' },
      { path: 'skating.pivotSpeed', min: 0, max: 4, step: 0.1, unit: 'm/s' },
      { path: 'skating.pivotTurnRate', min: 180, max: 1800, step: 20, unit: '°/s', scale: DEG },
      { path: 'skating.wallRestitution', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'skating.wallFriction', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'skating.playerRestitution', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'skating.radius', min: 0.2, max: 0.6, step: 0.01, unit: 'm' },
    ],
  },
  {
    id: 'cut',
    params: [
      { path: 'cut.minAngle', min: 30, max: 120, step: 1, unit: '°', scale: DEG },
      { path: 'cut.minSpeed', min: 1, max: 12, step: 0.5, unit: 'm/s' },
      { path: 'cut.gestureTime', min: 0.05, max: 0.5, step: 0.01, unit: 's' },
      { path: 'cut.prepTime', min: 0, max: 1.2, step: 0.05, unit: 's' },
      { path: 'cut.prepSpeedLoss', min: 0, max: 90, step: 5, unit: '%', scale: 100 },
      { path: 'cut.duration', min: 0.1, max: 0.6, step: 0.01, unit: 's' },
      { path: 'cut.redirect', min: 0, max: 100, step: 1, unit: '%', scale: 100 },
      { path: 'cut.noSprintTime', min: 0, max: 2, step: 0.05, unit: 's' },
      { path: 'cut.bodyTurn', min: 0, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'cut.exitAccel', min: 0, max: 40, step: 0.5, unit: 'm/s²' },
      { path: 'cut.exitTime', min: 0, max: 0.6, step: 0.01, unit: 's' },
      { path: 'cut.cooldown', min: 0, max: 3, step: 0.1, unit: 's' },
      { path: 'cut.onlyWithSprint', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'cut.ballSeparation', min: 0, max: 1.2, step: 0.05, unit: 'm' },
    ],
  },
  {
    id: 'dribble',
    params: [
      { path: 'dribble.baseSeparation', min: 0, max: 0.3, step: 0.01, unit: 'm' },
      { path: 'dribble.sprintSeparation', min: 0, max: 1.2, step: 0.05, unit: 'm' },
      { path: 'dribble.turnSeparation', min: 0, max: 1.2, step: 0.05, unit: 'm' },
      { path: 'dribble.turnThreshold', min: 0, max: 0.95, step: 0.05, unit: '' },
      { path: 'dribble.pressureSeparation', min: 0, max: 1.2, step: 0.05, unit: 'm' },
      { path: 'dribble.skidSeparation', min: 0, max: 1.2, step: 0.05, unit: 'm' },
      { path: 'dribble.controlAdvantage', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'dribble.followTime', min: 0, max: 0.2, step: 0.005, unit: 's' },
      { path: 'dribble.safeSeparation', min: 0.1, max: 1.5, step: 0.05, unit: 'm' },
      { path: 'dribble.lossRate', min: 0, max: 15, step: 0.5, unit: '/m·s' },
      { path: 'dribble.touchDistance', min: 0.5, max: 5, step: 0.1, unit: 'm' },
      { path: 'dribble.sprintSpeedWithBall', min: 6, max: 12, step: 0.1, unit: 'm/s' },
      { path: 'dribble.stickForward', min: 0.3, max: 0.9, step: 0.01, unit: 'm' },
      { path: 'dribble.stickSide', min: -0.4, max: 0.4, step: 0.01, unit: 'm' },
      { path: 'dribble.pickupRadius', min: 0.2, max: 1, step: 0.05, unit: 'm' },
      { path: 'dribble.pickupMaxHeight', min: 0.05, max: 1, step: 0.05, unit: 'm' },
      { path: 'dribble.pressureRadius', min: 0.5, max: 4, step: 0.1, unit: 'm' },
      { path: 'dribble.relockTime', min: 0, max: 1, step: 0.05, unit: 's' },
    ],
  },
  {
    id: 'pass',
    params: [
      { path: 'pass.tapTime', min: 0.08, max: 0.5, step: 0.01, unit: 's' },
      { path: 'pass.powerChargeTime', min: 0.1, max: 2, step: 0.05, unit: 's' },
      { path: 'pass.driveMaxHeight', min: 0.2, max: 2.5, step: 0.05, unit: 'm' },
      { path: 'pass.driveLaunchAngle', min: 5, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'pass.driveMaxSpeed', min: 8, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'pass.driveChargeMaxSpeed', min: 8, max: 40, step: 0.5, unit: 'm/s' },
      { path: 'pass.driveLandShort', min: 0, max: 5, step: 0.25, unit: 'm' },
      { path: 'pass.driveNoTargetDistance', min: 4, max: 30, step: 0.5, unit: 'm' },
      { path: 'pass.driveNoTargetMaxDistance', min: 6, max: 40, step: 0.5, unit: 'm' },
      { path: 'pass.groundArrivalSpeed', min: 1, max: 20, step: 0.5, unit: 'm/s' },
      { path: 'pass.groundShortArrivalSpeed', min: 1, max: 20, step: 0.5, unit: 'm/s' },
      { path: 'pass.groundShortFrom', min: 1, max: 15, step: 0.5, unit: 'm' },
      { path: 'pass.groundShortTo', min: 5, max: 30, step: 0.5, unit: 'm' },
      { path: 'pass.groundMinSpeed', min: 3, max: 25, step: 0.5, unit: 'm/s' },
      { path: 'pass.groundMaxSpeed', min: 10, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'pass.groundNoTargetSpeed', min: 5, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'pass.loftAngle', min: 10, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'pass.loftLandShort', min: 0, max: 4, step: 0.25, unit: 'm' },
      { path: 'pass.loftMaxSpeed', min: 10, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'pass.loftMinDistance', min: 2, max: 15, step: 0.5, unit: 'm' },
      { path: 'pass.loftMaxDistance', min: 8, max: 40, step: 1, unit: 'm' },
      { path: 'pass.lead', min: 0, max: 150, step: 5, unit: '%', scale: 100 },
      { path: 'pass.errorBase', min: 0, max: 10, step: 0.5, unit: '°', scale: DEG },
      { path: 'pass.errorSprint', min: 0, max: 20, step: 0.5, unit: '°', scale: DEG },
      { path: 'pass.errorPressure', min: 0, max: 20, step: 0.5, unit: '°', scale: DEG },
      { path: 'pass.errorOffBalance', min: 0, max: 25, step: 0.5, unit: '°', scale: DEG },
      { path: 'pass.errorLoft', min: 1, max: 3, step: 0.1, unit: '×' },
      { path: 'pass.errorPower', min: 0, max: 20, step: 1, unit: '%', scale: 100 },
      { path: 'pass.attributeAdvantage', min: 0, max: 1, step: 0.05, unit: '' },
    ],
  },
  {
    id: 'shot',
    params: [
      { path: 'shot.quickSpeed', min: 8, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'shot.minSpeed', min: 8, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'shot.maxSpeed', min: 8, max: 40, step: 0.5, unit: 'm/s' },
      { path: 'shot.tapTime', min: 0.08, max: 0.5, step: 0.01, unit: 's' },
      { path: 'shot.chargeTime', min: 0.1, max: 2, step: 0.05, unit: 's' },
      { path: 'shot.chargeSpeedFactor', min: 30, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'shot.mediumAimRange', min: 5, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'shot.lightAimRange', min: 5, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'shot.strongAimRange', min: 5, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'shot.aimMaxOff', min: 30, max: 180, step: 5, unit: '°', scale: DEG },
      { path: 'shot.postMargin', min: 0, max: 0.5, step: 0.01, unit: 'm' },
      { path: 'shot.farPost', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'shot.highHeight', min: 0.2, max: 1.2, step: 0.05, unit: 'm' },
      { path: 'shot.chipAngle', min: 10, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'shot.chipLandBeyond', min: 0, max: 3, step: 0.1, unit: 'm' },
      { path: 'shot.chipMaxSpeed', min: 5, max: 30, step: 0.5, unit: 'm/s' },
      { path: 'shot.errorBase', min: 0, max: 10, step: 0.25, unit: '°', scale: DEG },
      { path: 'shot.chargePrecision', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'shot.errorSprint', min: 0, max: 20, step: 0.5, unit: '°', scale: DEG },
      { path: 'shot.errorOffBalance', min: 0, max: 25, step: 0.5, unit: '°', scale: DEG },
      { path: 'shot.errorTurn', min: 0, max: 20, step: 0.5, unit: '°/rad', scale: DEG },
      { path: 'shot.turnFree', min: 0, max: 180, step: 5, unit: '°', scale: DEG },
      { path: 'shot.errorHeight', min: 0, max: 2, step: 0.05, unit: '×' },
      { path: 'shot.errorPower', min: 0, max: 20, step: 1, unit: '%', scale: 100 },
      { path: 'shot.mediumErrorFactor', min: 0.2, max: 1.5, step: 0.05, unit: '×' },
      { path: 'shot.strongErrorFactor', min: 0.2, max: 1.5, step: 0.05, unit: '×' },
      { path: 'shot.attributeAdvantage', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'shot.powerGain', min: 0, max: 30, step: 1, unit: '%', scale: 100 },
      { path: 'shot.reticleRange', min: 0, max: 40, step: 1, unit: 'm' },
      { path: 'shot.firstTouchError', min: 1, max: 3, step: 0.05, unit: '×' },
      { path: 'shot.redirectFree', min: 0, max: 180, step: 5, unit: '°', scale: DEG },
      { path: 'shot.errorRedirect', min: 0, max: 15, step: 0.5, unit: '°/rad', scale: DEG },
      { path: 'shot.turnRange', min: 0, max: 25, step: 0.5, unit: 'm' },
      { path: 'shot.turnMinAngle', min: 60, max: 180, step: 5, unit: '°', scale: DEG },
      { path: 'shot.turnTime', min: 0.05, max: 0.8, step: 0.01, unit: 's' },
      { path: 'shot.turnError', min: 1, max: 3, step: 0.05, unit: '×' },
    ],
  },
  {
    id: 'shotError',
    params: [
      { path: 'shot.ctxSprint', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'shot.ctxOffBalance', min: 0, max: 200, step: 5, unit: '%', scale: 100 },
      { path: 'shot.ctxAngle', min: 0, max: 200, step: 5, unit: '%', scale: 100 },
      { path: 'shot.ctxAngleFull', min: 15, max: 90, step: 5, unit: '°', scale: DEG },
      { path: 'shot.ctxDistance', min: 0, max: 20, step: 0.5, unit: '%/m', scale: 100 },
      { path: 'shot.ctxDistanceFree', min: 0, max: 20, step: 0.5, unit: 'm' },
      { path: 'shot.ctxPressure', min: 0, max: 300, step: 10, unit: '%', scale: 100 },
      { path: 'shot.ctxAssist', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'shot.sweetSpot', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'shot.sweetSpotStart', min: 50, max: 100, step: 1, unit: '%', scale: 100 },
      { path: 'shot.sweetSpotError', min: 0, max: 300, step: 10, unit: '%', scale: 100 },
    ],
  },
  {
    id: 'volley',
    params: [
      { path: 'volley.windowTime', min: 0.1, max: 1, step: 0.02, unit: 's' },
      { path: 'volley.good', min: 0.02, max: 0.3, step: 0.01, unit: 's' },
      { path: 'volley.powerBonus', min: 0, max: 50, step: 1, unit: '%', scale: 100 },
      { path: 'volley.badError', min: 0, max: 3, step: 0.1, unit: '×' },
      { path: 'volley.minHeight', min: 0, max: 0.5, step: 0.01, unit: 'm' },
      { path: 'volley.maxHeight', min: 0.3, max: 2, step: 0.05, unit: 'm' },
      { path: 'volley.reach', min: 0.3, max: 1.5, step: 0.05, unit: 'm' },
      { path: 'volley.easySpeed', min: 0, max: 20, step: 0.5, unit: 'm/s' },
      { path: 'volley.hardSpeed', min: 5, max: 40, step: 0.5, unit: 'm/s' },
      { path: 'volley.idealLow', min: 0, max: 1, step: 0.05, unit: 'm' },
      { path: 'volley.idealHigh', min: 0.2, max: 1.5, step: 0.05, unit: 'm' },
      { path: 'volley.lowPenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'volley.highPenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'volley.lowTarget', min: 0.05, max: 1, step: 0.05, unit: 'm' },
      { path: 'volley.lookahead', min: 0.2, max: 1.5, step: 0.05, unit: 's' },
    ],
  },
  {
    id: 'receive',
    params: [
      { path: 'receive.easySpeed', min: 0, max: 20, step: 0.5, unit: 'm/s' },
      { path: 'receive.hardSpeed', min: 8, max: 40, step: 0.5, unit: 'm/s' },
      { path: 'receive.controlAdvantage', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'receive.randomness', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'receive.heavyAt', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.reboundAt', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.missAt', min: 0, max: 3, step: 0.05, unit: '' },
      { path: 'receive.behindPenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.heightPenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.bouncePenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.bounceSpeed', min: 0.5, max: 8, step: 0.25, unit: 'm/s' },
      { path: 'receive.sprintPenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.offBalancePenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.stretchPenalty', min: 0, max: 2, step: 0.05, unit: '' },
      { path: 'receive.reach', min: 0.2, max: 2, step: 0.05, unit: 'm' },
      { path: 'receive.maxRelSpeed', min: 10, max: 50, step: 0.5, unit: 'm/s' },
      { path: 'receive.heavySeparation', min: 0, max: 1.5, step: 0.05, unit: 'm' },
      { path: 'receive.reboundKeep', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'receive.reboundSpread', min: 0, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'receive.reboundLift', min: 0, max: 5, step: 0.1, unit: 'm/s' },
      { path: 'receive.lockTime', min: 0, max: 1, step: 0.05, unit: 's' },
      { path: 'receive.firstTouchWindow', min: 0, max: 1, step: 0.05, unit: 's' },
      { path: 'receive.firstTouchError', min: 1, max: 4, step: 0.1, unit: '×' },
      { path: 'receive.showFeedback', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'receive.feedbackTime', min: 0.1, max: 2, step: 0.05, unit: 's' },
    ],
  },
  {
    id: 'wall',
    params: [
      { path: 'wall.assist', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'wall.maxDistance', min: 3, max: 25, step: 0.5, unit: 'm' },
      { path: 'wall.lightCone', min: 5, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'wall.mediumCone', min: 5, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'wall.strongCone', min: 5, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'wall.arrivalSpeed', min: 3, max: 25, step: 0.5, unit: 'm/s' },
      { path: 'wall.lead', min: 0, max: 1.5, step: 0.05, unit: '' },
      { path: 'wall.sprintGain', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'wall.minSpeed', min: 0, max: 6, step: 0.25, unit: 'm/s' },
      { path: 'wall.standingAhead', min: 0, max: 8, step: 0.25, unit: 'm' },
      { path: 'wall.minCorrection', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'wall.errorFactor', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'wall.reach', min: 0.2, max: 2, step: 0.05, unit: 'm' },
      { path: 'wall.showMarkers', min: 0, max: 1, step: 1, unit: '', toggle: true },
    ],
  },
  {
    id: 'assist',
    params: [
      { path: 'assist.lightCone', min: 5, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'assist.lightCorrection', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'assist.mediumCone', min: 5, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'assist.mediumCorrection', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'assist.mediumArrivalBonus', min: -4, max: 8, step: 0.5, unit: 'm/s' },
      { path: 'assist.strongCone', min: 5, max: 90, step: 1, unit: '°', scale: DEG },
      { path: 'assist.strongCorrection', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'assist.targetRing', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'assist.lightSpaceRespect', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'assist.mediumSpaceRespect', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'assist.strongSpaceRespect', min: 0, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'assist.spaceCone', min: 0, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'assist.spaceMinTime', min: 0, max: 1.5, step: 0.05, unit: 's' },
      { path: 'assist.spaceMaxTime', min: 0.5, max: 4, step: 0.1, unit: 's' },
      { path: 'assist.spaceArrivalSpeed', min: 3, max: 20, step: 0.5, unit: 'm/s' },
      { path: 'assist.spaceLaunchMin', min: 3, max: 20, step: 0.5, unit: 'm/s' },
      { path: 'assist.spaceChargedArrivalSpeed', min: 3, max: 30, step: 0.5, unit: 'm/s' },
      { path: 'assist.spaceDeadzone', min: 0, max: 30, step: 1, unit: '°', scale: DEG },
      { path: 'assist.spaceRamp', min: 1, max: 40, step: 1, unit: '°', scale: DEG },
      { path: 'assist.spaceMinSpeed', min: 0.5, max: 8, step: 0.5, unit: 'm/s' },
    ],
  },
  {
    id: 'passArrow',
    params: [
      { path: 'passArrow.minLength', min: 0.3, max: 4, step: 0.1, unit: 'm' },
      { path: 'passArrow.maxLength', min: 1, max: 10, step: 0.25, unit: 'm' },
      { path: 'passArrow.fullSpeed', min: 8, max: 35, step: 0.5, unit: 'm/s' },
      { path: 'passArrow.width', min: 0.04, max: 0.5, step: 0.01, unit: 'm' },
      { path: 'passArrow.startOffset', min: 0, max: 3, step: 0.1, unit: 'm' },
      { path: 'passArrow.afterTime', min: 0, max: 1.5, step: 0.05, unit: 's' },
    ],
  },
  {
    id: 'mates',
    params: [
      { path: 'mates.switchControl', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'mates.lostPassSwitch', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'mates.autoSwitch', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'mates.switchMargin', min: 0, max: 5, step: 0.25, unit: 'm' },
      { path: 'mates.switchDelay', min: 0, max: 1.5, step: 0.05, unit: 's' },
      { path: 'mates.switchCooldown', min: 0, max: 3, step: 0.1, unit: 's' },
      { path: 'mates.autoReceive', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'mates.move', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'mates.switchLatchAngle', min: 10, max: 120, step: 5, unit: '°', scale: DEG },
      { path: 'mates.returnDelay', min: 0, max: 2, step: 0.05, unit: 's' },
      { path: 'mates.quickReturn', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'mates.quickReturnSpeed', min: 0.5, max: 8, step: 0.5, unit: 'm/s' },
      { path: 'mates.quickReturnDelay', min: 0, max: 1, step: 0.05, unit: 's' },
      { path: 'mates.supportAhead', min: -4, max: 8, step: 0.5, unit: 'm' },
      { path: 'mates.supportSide', min: 2, max: 9, step: 0.5, unit: 'm' },
      { path: 'mates.supportSpeed', min: 20, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'mates.arriveRadius', min: 0.5, max: 4, step: 0.1, unit: 'm' },
      { path: 'mates.interceptRadius', min: 0.5, max: 5, step: 0.1, unit: 'm' },
      { path: 'mates.interceptMaxTime', min: 0.5, max: 4, step: 0.1, unit: 's' },
      { path: 'mates.interceptSpeed', min: 20, max: 100, step: 5, unit: '%', scale: 100 },
      { path: 'mates.settleRadius', min: 0, max: 1.5, step: 0.05, unit: 'm' },
      { path: 'mates.settleTime', min: 0, max: 1, step: 0.05, unit: 's' },
      { path: 'mates.fetchRadius', min: 0, max: 8, step: 0.5, unit: 'm' },
      { path: 'mates.speedVariation', min: 0, max: 50, step: 5, unit: '%', scale: 100 },
      { path: 'mates.spotVariation', min: 0, max: 4, step: 0.25, unit: 'm' },
    ],
  },
  {
    id: 'ball',
    params: [
      { path: 'ball.boardRestitution', min: 0.2, max: 1, step: 0.05, unit: '' },
      { path: 'ball.rollingDecel', min: 0, max: 3, step: 0.05, unit: 'm/s²' },
      { path: 'ball.rollingDrag', min: 0, max: 0.5, step: 0.01, unit: '/s' },
      { path: 'ball.floorRestitution', min: 0, max: 0.9, step: 0.05, unit: '' },
      { path: 'ball.floorFriction', min: 0, max: 0.6, step: 0.02, unit: '' },
      { path: 'ball.boardFriction', min: 0, max: 0.6, step: 0.02, unit: '' },
      { path: 'ball.boardJitter', min: 0, max: 15, step: 0.5, unit: '°', scale: DEG },
      { path: 'ball.postRestitution', min: 0.1, max: 1, step: 0.05, unit: '' },
      { path: 'ball.netRestitution', min: 0, max: 0.6, step: 0.05, unit: '' },
      { path: 'ball.netDamping', min: 1, max: 20, step: 0.5, unit: '/s' },
      { path: 'ball.playerRestitution', min: 0, max: 1, step: 0.05, unit: '' },
      { path: 'ball.airDrag', min: 0, max: 0.03, step: 0.0005, unit: '/m' },
      { path: 'ball.heavy', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'ball.heavyBoardRestitution', min: 0.2, max: 1, step: 0.05, unit: '' },
      { path: 'ball.heavyBoardFriction', min: 0, max: 0.6, step: 0.01, unit: '' },
      { path: 'ball.heavyBoardJitter', min: 0, max: 15, step: 0.5, unit: '°', scale: DEG },
      { path: 'ball.heavyFloorRestitution', min: 0, max: 0.9, step: 0.05, unit: '' },
      { path: 'ball.heavyPostRestitution', min: 0.1, max: 1, step: 0.05, unit: '' },
      { path: 'ball.visualScale', min: 1, max: 3, step: 0.1, unit: '×' },
      { path: 'ball.visualRefDistance', min: 8, max: 40, step: 0.5, unit: 'm' },
      { path: 'ball.markerRadius', min: 0, max: 0.6, step: 0.02, unit: 'm' },
      { path: 'ball.ghost', min: 0, max: 1, step: 1, unit: '', toggle: true },
      { path: 'ball.ghostOpacity', min: 0.1, max: 1, step: 0.05, unit: '' },
      { path: 'ball.ghostDistance', min: 0.5, max: 20, step: 0.5, unit: 'm' },
      { path: 'ball.ghostSize', min: 1, max: 4, step: 0.1, unit: '×' },
    ],
  },
  {
    id: 'input',
    params: [
      { path: 'input.sprintThreshold', min: 70, max: 130, step: 1, unit: '%', scale: 100 },
      { path: 'input.joystickCurve', min: 1, max: 3, step: 0.1, unit: '' },
      { path: 'input.joystickDeadZone', min: 0, max: 40, step: 1, unit: '%', scale: 100 },
      { path: 'input.sprintHysteresis', min: 0, max: 15, step: 1, unit: '%', scale: 100 },
      { path: 'input.bufferTime', min: 0, max: 0.4, step: 0.01, unit: 's' },
      { path: 'input.passDragDistance', min: 15, max: 200, step: 5, unit: 'px' },
      { path: 'input.passDragAngle', min: 0, max: 60, step: 1, unit: '°', scale: DEG },
      { path: 'input.joystickRadiusPx', min: 30, max: 140, step: 2, unit: 'px' },
      { path: 'input.joystickZone', min: 0.3, max: 0.8, step: 0.05, unit: '' },
      { path: 'input.gamepadDeadZone', min: 0, max: 0.5, step: 0.01, unit: '' },
    ],
  },
  {
    id: 'buttons',
    params: (['dribble', 'pass', 'shoot', 'switch'] as const).flatMap((b) => [
      { path: `buttons.${b}Bottom`, min: 0, max: 300, step: 2, unit: 'px' },
      { path: `buttons.${b}Right`, min: 0, max: 450, step: 2, unit: 'px' },
      { path: `buttons.${b}Size`, min: 50, max: 160, step: 2, unit: 'px' },
    ]),
  },
  { id: 'cameraTv', params: cameraPresetParams('cameraTv') },
  { id: 'cameraClose', params: cameraPresetParams('cameraClose') },
  { id: 'cameraTactical', params: cameraPresetParams('cameraTactical') },
  {
    id: 'camera',
    params: [{ path: 'camera.transitionTime', min: 0, max: 2, step: 0.05, unit: 's' }],
  },

];

export const TUNING_PARAMS: TuningParamMeta[] = TUNING_SECTIONS.flatMap((s) => s.params);
